### ISSUE TITLE
What could be the problem? Bad login, Error 404

### ISSUE THREAD

**Issue by Goosegit11** [staliox/pyxui#28]
Code:

```python
from pyxui import XUI
import json
import urllib3

urllib3.disable_warnings()


# Basic:
xui = XUI(
    full_address="https://<ip>:<port>/<webbasepath>",
    panel="sanaei", # Your panel name, "alireza" or "sanaei"
    https=False
)

from pyxui.errors import BadLogin

USERNAME = 'user'
PASSWORD = 'pass'

try:
  xui.login(USERNAME, PASSWORD)
except BadLogin:
  print("Bad login")

get_inbounds = xui.get_inbounds()

print(json.dumps(get_inbounds, indent=4))
```

Error:
```python
Bad login
Traceback (most recent call last):
  File "/root/py-scripts/main.py", line 48, in <module>
    get_inbounds = xui.get_inbounds()
  File "/root/py-scripts/lib/python3.10/site-packages/pyxui/methods/inbounds.py", line 28, in get_inbounds
    return self.verify_response(response)
  File "/root/py-scripts/lib/python3.10/site-packages/pyxui/methods/base.py", line 53, in verify_response
    raise errors.NotFound()
pyxui.errors.NotFound: [NOT_FOUND] Error 404 has been received.
```

Username and password are right.

**Comment by Goosegit11** [comment]
I added `session_string`  to the `xui` and when logging in it says ALREADY LOGGED. 
Then I remove the code with login and still the same 'Not found' error. I can't get inbounds

**Comment by Goosegit11** [comment]
Going to the `https://ip:port/basepath/panel/api/inbounds/list` in browser works, returns json with inbounds.

**Comment by staliox** [comment]
> Going to the `https://ip:port/basepath/panel/api/inbounds/list` in browser works, returns json with inbounds.

1st make sure your end of url doesn't contain /
2nd which panel do you use, alireza or sanaei?

**Comment by Goosegit11** [comment]
https://github.com/iwatkot/py3xui

I found this library, it works. Thanks for your contribution anyway 👍
